# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/crypted";
      fsType = "ext4";
    };

  boot.initrd.luks.devices.crypted.device = "/dev/sda1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C9B4-43EC";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4c81ac23-2c32-45bd-a3ed-152609fae2a2"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
